### ISSUE TITLE
tasmocompiler stops working with Tasmota version 10 introduced

### ISSUE THREAD

**Issue by ilexpl01** [benzino77/tasmocompiler#226]
Hi,

Today Tasmota v10.0.0 Norman was introduced. Since that time tasmoCompiler stops working.

![image](https://user-images.githubusercontent.com/67930801/137884954-1a803204-77e1-45f0-b22c-47179b7a84ed.png)

Any hint ?

**Comment by benzino77** [comment]
That's because Tasmota introduced "strange" tag to its repo:

![image](https://user-images.githubusercontent.com/15658235/137902137-ee2d6880-3259-409d-9158-fd91a874a4d7.png)

Anyway it is now handled by TasmoCompiler and you should be able to compile v9.5.x version (development and v10.0.0 is still incompatible with TC). 
You have to wait a while for new docker image containing a fix.
