### ISSUE TITLE
Tasmota 12.2.0 not available

### ISSUE THREAD

**Issue by AndreKR** [benzino77/tasmocompiler#305]
The latest stable version of Tasmota is 12.2.0 but the latest version available in TasmoCompiler is 12.1.1.

### Tasmota repository:

![image](https://user-images.githubusercontent.com/1188538/200044777-b69c3a40-996a-4e29-b98c-d1fed9f303a3.png)

### Tasmocompiler on Gitpod:

![image](https://user-images.githubusercontent.com/1188538/200044630-09d8a971-90c2-4514-b5ab-69d6520f2e97.png)

**Comment by benzino77** [comment]
Hi Andre,

That is because there are braking changes between Tasmota `v12.0.x/v12.1.x` and Tasmota `v12.2.x` and it makes TasmoCompiler incompatible with `v12.2.x`. 
I encourage you to read my answer [here](https://github.com/benzino77/tasmocompiler/discussions/301#discussioncomment-4011889).

`developmnet` branch of Tasmocompiler is compatible (at  least it was few days ago) with `development` branch of Tasmota. If it doesn't bother you, you can go this way.

**Comment by AndreKR** [comment]
Ah, I see.

I actually tried the `development` branch, but that could *only* build `development` Tasmota, which is already 166 commits ahead of 12.2.0.

**Comment by Jason2866** [comment]
Happy to announce release of Tasmota v12.3.0

**Comment by aldweb** [comment]
Hello, I am a big fan of Tasmocompiler which I use to upgrage my custom builds whenever a new Tasmota release is made available. I hope Tasmocompiler will soon be able to compile v12.3.x
Keep up the good work.

**Comment by benzino77** [comment]
https://github.com/benzino77/tasmocompiler/discussions/316

**Comment by benzino77** [comment]
I've uploaded v10.0.0 version of TasmoCompiler with support for Tasmota v12.3.x

**Comment by aldweb** [comment]
This is very good news, thank you so much!
