### ISSUE TITLE
Option to create a minimal firmware with Wifi settings

### ISSUE THREAD

**Issue by bovirus** [benzino77/tasmocompiler#76]
@benzino77 

Could be possible with tasmocompiler to create a tasmota minimal firmware (max 500KB) just with web interface and pre-configured settings (Wifi SSID and password?

Could be useful to create minimal tasmota firmware to flash a new Sonoff device.

How can do that?

Thanks.

**Comment by ascillato** [comment]
The Tasmota firmware type called minimal is just for updating. You don't need to have credentials on it.

If you refer to a Tasmota version with a small flash usage, that is Tasmota Lite version that don't have any sensors support and it was made specially for sonoff basic.

**Comment by bovirus** [comment]
@ascillato 

Thanks for the info.

My scope is to create a tasmota basic firmware (under 500kb) for the first flash from standard Sonoff basic firmware (not tasmota).

This tasmota basic firmware should be have webui, set Wifi SSID/password (in dhcp) and connect to wifi.

**Comment by ascillato** [comment]
The Tasmota Lite version is under 500kb. Just use the `define FIRMWARE_LITE`

Anyway, why are you putting that 500kb limit?
Tasmota supports updating from compressed binaries too, so the limit for doing an OTA upgrade is higher than 500kb

**Comment by bovirus** [comment]
@ascillato.

It's only for first flash in a device with original manufacturer firmware.

Ex. if you want to flash a Sonoff Basic R3 with ithead original firmware via serial console you should use a tasmota firmware max 500KB.

**Comment by ascillato** [comment]
Great, so Tasmota Lite version should do the job :+1:

**Comment by ascillato** [comment]
> Ex. if you want to flash a Sonoff Basic R3 with ithead original firmware via serial console you should use a tasmota firmware max 500KB.

By the DIY OTA method from iTead, yes, you need a firmware with less than 500KB.

But by serial cable you can use the whole flash space (1mb on Sonoff basics).

Anyway, the Tasmota Lite version should do the job on any flashing method :+1:

**Comment by bovirus** [comment]
@ascillato 

Thanks for the info.
I got the (wrong) info about max 500Kb firmware for flash usings serial console in a ithead forum.

**Comment by benzino77** [comment]
Putting only WiFi credentials and compile the new firmware with all default options in TasmoCompiler resulting in 492KB bin file size.
```shell
❯ du -k firmware.bin
492     firmware.bin
```
Mentioned by Adrian setting `#define FIRMWARE_LITE` in `Custom parameters` step resulting in even smaller bin file size:
```shell
❯ du -k firmware.bin
432     firmware.bin
```

**Comment by bovirus** [comment]
My standard module for compilation are 

**_Web GUI/Timers/Rules_** (standard) + **_Alexa_**

and with these modules the firmware is over 500KB.
 
If I use 

#define FIRMWARE_LITE

in "Custom Setting" will I disable one of these functions

Web GUI/Timers/Rules/Alexa

I will receive soon a Sonoff RF module.
Which is the right module to enable in atsmocompiler during compilation to handle RF part pf Sonoff?

Thanks.

**Comment by benzino77** [comment]
I really don't get it. You want a small firmware size but on the other side you are not ready to resign of some features - it is in my opinion not doable. You cannot (in most cases) "have cookie and eat cookie". 
Try to find answer to your question how to get less than 500KB bin file with features you want on Tasmota [Discord ](https://discord.gg/Ks2Kzd4) channle or [Tasmota Google Group](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/sonoffusers)


Sonoff RF require `#define USE_SONOFF_RF` which is not disabled by TasmoCompiler and is enabled by default by [Tasmota](https://github.com/arendst/Tasmota/blob/5e4554e92775c844241fe15e5bd2c40996901aac/tasmota/my_user_config.h#L434)

**Comment by bovirus** [comment]
@benzino77 

For me is not really true.
I'm building a light (not basic) firmware.
It emans a firmware that contains what I need and not what I don't need.
The full firmware contains a lot of hardware modules/drivers that I don't use and I cannot disable during compilation (unless to use #define FIRMWARE_LITE) 

I want to build a firmware with the functions and hardware drivers that I need (nothing else).

**Comment by benzino77** [comment]
You don't have to put 
```
#define USE_RULES
#define USE_TIMERS
``` 
in `Custom parameters` step because those features are on list of features which can be enabled or disabled in step 3!!!

**`Custom parameters` is for things which are not available by step 3**. 

At the end of the compilation you can download `user_config_override.h` file to see what TasmoCompiler modifies. Based on that and features enabled by default by Tasmota (this can be found [here](https://github.com/arendst/Tasmota/blob/5e4554e92775c844241fe15e5bd2c40996901aac/tasmota/my_user_config.h). 
you can then turn on and off features (not available to choose in step 3) by `Custom parameters` step.

**Comment by bovirus** [comment]
@benzino77 
Thanks for the info.

#define FIRMWARE_LITE

has an hiogher priority that options elected in Step3 then I renabled Tiems/Rules.
Now I undrestiood that it's enough

#define FIRMWARE_LITE

without other options.

In Step3 which is (if there is) the option that match

#define USE_SONOFF_RF

to enable RF function for Sonoff?

**Comment by benzino77** [comment]
`Custom parameters` would be added at the end of `user_config_override.h` file - see issue #73. 
If you disable feature X in step 3 and then enable it in step 4, the resulting firmware will have feature X enabled.

Support for Sonoff RF, as stated before, is enabled by default.

Please read carefully Tasmota [my_user_config.h ](https://github.com/arendst/Tasmota/blob/5e4554e92775c844241fe15e5bd2c40996901aac/tasmota/my_user_config.h) file and compare it with `user_config_override.h` file provided by TasmoCompiler.

**Comment by bovirus** [comment]
@benzino77 

Thanks for the info that clarify the priority of the process.

Then to have a light firmware for Sonoff Basic/Basic RF with webui and Alexa enabled it's enogh to enalble in step3

- Alexa
- Rules
- Timers
- Web ui

and in custom setting

- #define FIRMWARE_LITE

Thanks.

**Comment by ascillato** [comment]
As an advice for making a bit easier the maintenance of the software on your devices (upgrading, etc) it is better to flash the standard version of Tasmota (that have all the features you have asked before) and update with the standard from there. That will save you a lot of time.
For example, in my home I have 36 Tasmota devices and all have the exact same firmware. I have a mix of Shellys, sonoffs basics, nodemcu, etc. All with the same version. So, while updating I just use the same version for all. 
All the settings will be retained while upgrading. It is not needed to be hardcoded them in the firmware. 
For the case of the first flash, if you want, you can flash a firmware with the wifi/mqtt credentials (so as to save you one step - I do the same), but from there you can use the standard.
That will make your life easier. 
Also, if you want, you can perform a config backup of each device. In the case any of the hardware fails, you can change it, flash Tasmota and just load the configuration for that particular device. In the case of the configuration, yes, you are going to have one file for each device.
Besides all these, I disable the setoptions 36 and 65 in order to not loose the configuration if there is a power fluctuation.
Just a tip. Hope it helps.

**Comment by bovirus** [comment]
Thanks a lot for these intersting info.

Of course if you want to flash a new version of tasmota firmware (>500KB) you have to do in two step

Flash new tasmota minimal firmware
Flash new tasmota full firmware

Is it right?

What's about setoptions 36 and 65?

Thanks.

**Comment by ascillato** [comment]
If you flash as the first step the Tasmota version called minimal, your device will brick and you will need to erase all flash and flash the full version. The minimal is just for updating. 
The Lite version will work without any problem. 
But if you are flashing by serial, you can flash the complete version at once. No need for intermediate steps. Intermediate steps are only for OTA updates. Also, as Tasmota now supports compressed bins, you don't need intermediate steps any more.

**Comment by ascillato** [comment]
Those setoptions are for resetting the configuration of the device to the defaults of the firmware in case of boot hung or in case of 4 fast power energizing cycles (on off on off... )
For more info on them, you can check the docs at Tasmota.com

**Comment by bovirus** [comment]
@ascillato 

Did you have a link that point to setoptions 36 and 65 odcumentation?
Thanks.

**Comment by ascillato** [comment]
No, setoption39 has nothing to do with bootloop protection. 

The ones I was talking about were:

So36 0
So65 1

**Comment by bovirus** [comment]
@ascilalro

How can set them tasmocompielr with Custom Settings?

**Comment by ascillato** [comment]
Custom settings are the ones defined in my_user_config.h
Search in that file which name every define has that you are interested in, and you can override them to fit your needs in the same way you did with #define FIRMWARE_LITE
Not everything can be defined in the precompiled bin, but most Tasmota options are.
