### ISSUE TITLE
new esp8266 core

### ISSUE THREAD

**Issue by 5chufti** [benzino77/tasmocompiler#81]
Hi,
sorry to bother again, but essential new versions - hopefully stability improving - on esp8266 core version are not selectable.

(n.b.: I don't understand why tasmota has to be on bleeding edge for esp8266 cores when versions since 2.5 deteriorate regarding wifi stability, looking at Issues over there)

**Comment by ascillato** [comment]
> I don't understand why tasmota has to be on bleeding edge for esp8266 cores

I understand but we do because it is really necessary. Those updates have mainly include:

Security bugs fixed
PWM crashes fixed
Memory management crash fixed
iRAM usage fixed
Increased Free RAM
Between many others 

But mainly because of security issues. When any security issue is revealed, we must update and solve it. We can not leave a known insecure version. It is too risky for anyone not aware of those issues.

**Comment by benzino77** [comment]
New docker images will be available soon. For now you can use gitpod approach.

**Comment by 5chufti** [comment]
thank you for the prompt action :thumbsup:
