### ISSUE TITLE
select NodeMCU (4MB) 

### ISSUE THREAD

**Issue by Mark-Muc** [benzino77/tasmocompiler#85]
I tired to compile a version for NodeMCU (4MB) without any flags .. simply nothing selected .. only the things already selected.
The firmware compiles without a problem (no errors) .. then i load it with the new tasmotizer-1.1c.exe via USB to a LoLin new NodeMcu V3. Then I add WiFi und Module generic to the NodeMcu ..it restarts but it won't show up in my network.
If i take the same settings ..using Sonoffs (1mb) to compile it works fine.
Any Idea? can someone verifiy.
Thanks
Mark_Muc

**Comment by benzino77** [comment]
See what is printed on the serial console. You can use [Termite ](https://www.compuphase.com/software_termite.htm) program.

**Comment by Mark-Muc** [comment]
installed Termite .. and it is working . try to flash a NodeMCU compiled version .. sent the WiFi data ..reboot and it simply say. Nothing

**Comment by benzino77** [comment]
Try not to use Tasmotizer. 
Try to use nodemcuflasher or esptool command line tool.

**Comment by benzino77** [comment]
It can be related to Tasmotizer: [issue link](https://github.com/tasmota/tasmotizer/issues/51)

**Comment by Mark-Muc** [comment]
many thanks benzino77!!
I took the nodemcuflasher, use the devault settings and it works fine!!
my settings are:
Baudrate; 230400
Flash size: 4MByte
Flash speed: 40MHz
SPI Mode: DIO
(default settings)

in Config:
0x00000

Thanks again and mybe it helps others too ... like u mentioned in the issue link!!
Mark_Muc

**Comment by ascillato** [comment]
Hi, there is a wrong parameter in your flashing. DIO can produce an incorrect flashing (with wifi issues and watchdogs). Tasmota is compiled to be used with DOUT.

Another thing is that there is no point in compiling for 4MB. Tasmota won't use the extra space. 
In a 4MB device you can flash the 1MB firmware right away. You can have all your devices (1MB, 2MB, 4MB, etc) all with the exact same firmware. There is no gain in having different memory map for different devices due to the extra space is not going to be used (side note: the esp8266 has a hardware limitation that won't execute a firmware bigger than 1MB. The rest of flash can be used ONLY for storing data, not program)

**Comment by Mark-Muc** [comment]
ok thanks for your comment ascillato!!

**Comment by benzino77** [comment]
@ascillato it can make sense in case you want to upgrade firmware larger than 500kB in one step and I think this is the only reason to have firmware compiled for 4MB device.

**Comment by ascillato** [comment]
Yes, that is the only advantage, but, as now tasmota supports to OTA upgrade using compressed firmware, that is not a restriction anymore.

Also, Tasmota supports OTAMagic that when you try to update a large firmware using OTAurl, Tasmota will do automatically the 2 steps upgrade using a minimal version and then the requested full firmware.
